WIP Update Readme file
CraftAcademy/slow_food_online_feb_17 pull request #11
Opened 2017-04-01 21:02 UTC by casperjureskog

**PT Story:** https://www.pivotaltracker.com/story/show/142774665

**Changes proposed in this PR:**

# SloFo

This is middcorse prodject for CraftAcademy Class Feb-april 2017

**Pivotal Tracker**
[Pivotal Tracker for SloFo](https://www.pivotaltracker.com/n/projects/1996373).

**GitHub**
This site reside [GitHub Pages](https://github.com/CraftAcademy/slow_food_online_feb_17).

###Installing

Fork and clone repo, then run:

```
$ bundle install
```
Then:

```
$rake db:migrate
```

###Deployment

We are using [Semaphoreci CI](https://semaphoreci.com)  for continous integration and [Heroku](http://heroku.com/)

##Information aboute prodject:

* Ruby version
  Ruby 5.0.2

* System dependencies
  acts_as_shopping_cart  https://github.com/crowdint/acts_as_shopping_cart

* Configuration
  Ruby on rails
  Haml

* Database creation
  rails db:create

* Database initialization
  rails db:migrate

* How to run the test suite
* Tests: **rake** to run all test
         **rspec** to run spec test
         **cucumber** to run feature test

* Services (job queues, cache servers, search engines, etc.)

* Deployment instructions

* ...

2017-04-03 02:55 UTC, sigu requested changes

2017-04-03 02:55 UTC, sigu commented on README.md
> +  Ruby 5.0.2
This is actually the version of rails we are using, not ruby

2017-04-03 02:55 UTC, sigu commented on README.md
>  * Configuration
Title doesnt match the content

2017-04-03 03:05 UTC, sigu commented
You need to cover only the important things in the Readme file
1. What is this project about?
2. What is the development and deployment process?
3. How can someone contribute to the project?
4. How does one run tests?
5. What are some of the basic things before submitting a pull request that must be done? e.g all tests must be passing

This list is not in any particular order, it just gives you the idea of what is to be included in the file. 

Have a look at the following Readme files
https://github.com/AgileVentures/WebsiteOne
https://github.com/AgileVentures/asyncvoter-api

2017-04-03 06:48 UTC, casperjureskog commented on README.md
> +  Ruby 5.0.2
Ah true

2017-04-03 06:48 UTC, casperjureskog commented on README.md
>  * Configuration
hopp fully it will be :-)

2017-04-03 11:18 UTC, sigu commented on README.md
> +```
just for your information you can always add the type of hightlighting you want for the code for example in this scenario you can add the word `bash` after the triple backticks ``` bash

2017-04-03 11:55 UTC, tochman commented
Any action on this @casperjureskog

2017-04-03 12:08 UTC, casperjureskog commented on README.md
> +```
im not sure what you men :-/

2017-04-04 07:41 UTC, fottander approved these changes
Good so far.

2017-04-04 07:59 UTC, merged