WIP Rating to restaurants
CraftAcademy/slow_food_online_feb_17 pull request #25
Opened 2017-04-06 15:00 UTC by Scharrre97

https://www.pivotaltracker.com/n/projects/1996373/stories/142505545

As a visitor
In order to show what I think of a restaurant
I would like to be able to rate restaurants from  1-5

2017-04-07 12:11 UTC, sigu approved these changes

2017-04-07 12:11 UTC, sigu commented on app/controllers/shopping_carts_controller.rb
>    def complete
This method already looks too long and too nested. Can we have another method for rating to be called within complete action?

2017-04-07 12:11 UTC, sigu commented on app/views/index/index.html.haml
> -      = restaurant.name
Is this in scope for this issue?

2017-04-07 12:11 UTC, sigu commented on app/views/devise/sessions/new.html.haml
> +        = f.submit "Sign in"
Is this in scope for this issue?

2017-04-07 12:11 UTC, sigu commented on spec/models/rating_spec.rb
> +    it { is_expected.to belong_to :restaurant }
Any dependancy on the parent? 
http://guides.rubyonrails.org/association_basics.html#belongs-to-association-reference

2017-04-07 12:36 UTC, sigu submitted a review, later dismissed
I meant to `request changes` and not `approve`

2017-04-08 11:25 UTC, casperjureskog commented on spec/models/rating_spec.rb
> +    it { is_expected.to belong_to :restaurant }
yes restaurang have
´´´
it { is_expected.to have_one :rating }
´´´

2017-04-10 08:03 UTC, tochman requested changes

2017-04-10 08:03 UTC, tochman commented on app/controllers/restaurants_controller.rb
> +    Rating.create(restaurant: @restaurant , rating: 3.0 , counter: 30)
??

2017-04-10 08:03 UTC, tochman commented on app/controllers/restaurants_controller.rb
> +    Rating.create(restaurant: @restaurant , rating: 3.0 , counter: 30)
You could add this as `after_create` in the Restaurant model.

2017-04-10 08:03 UTC, tochman commented on app/controllers/shopping_carts_controller.rb
> +  end
I think I would like a separate controller for CRUD actions on Rating

2017-04-10 08:03 UTC, tochman commented on app/controllers/shopping_carts_controller.rb
> +    @rating = Rating.find_by(restaurant_id: @cart.shopping_cart_items[0].item.menu.restaurant.id)
Please clear this out and keep the `get_shopping_cart` to do one thing only.

2017-04-10 08:03 UTC, tochman commented on app/views/shopping_carts/complete.html.haml
> +  = form_for [@rating], :html => {class: cart_item.item.menu.restaurant.name} , url: rate_path(cart_id: @cart.id,rest_id: cart_item.item.menu.restaurant.id),method: 'post' do |f|
Is this the right place to have this form?

2017-04-10 08:03 UTC, tochman commented on app/views/shopping_carts/complete.html.haml
> +    = f.select(:rating, ['1','2','3','4','5'])
I would add this array as a constant on the `Rating` model

```
class Rating < ...
  RATING_VALUES = [1, 2, 3, 4, 5]
...
end
```
Use:
```
= f.select(:rating, Rating.RATING_VALUES)
```

2017-04-10 08:03 UTC, tochman commented on app/views/shopping_carts/complete.html.haml
> +    = f.select(:rating, ['1','2','3','4','5'])
Als, add a validation for value being included in RATING_VALUES

2017-04-10 08:03 UTC, tochman commented on config/routes.rb
> +  post "/complete/id", controller: :shopping_carts, action: :rate, as: :rate
Revisit this

2017-04-10 08:03 UTC, tochman commented on db/migrate/20170406140542_add_ratings_association_to_restaurant.rb
> +    add_reference :ratings, :restaurant, foreign_key: true
We probably want to know WHO created the rating

2017-04-10 08:03 UTC, tochman commented on db/seeds.rb
> +t = Restaurant.create(name: name,
Variable naming feels weird 😃

2017-04-10 08:03 UTC, tochman commented on db/seeds.rb
> +# Restaurant.delete_all
It's probably `Restaurant.destroy_all`

2017-04-10 08:03 UTC, tochman commented on features/rating_restaurants.feature
> +      Then I should see "Rating 2.97"
I would revisit this scenario.

2017-04-10 08:03 UTC, tochman commented on features/restaurant_reg.feature
> +    Then I should see "Leffes pizza" start rating should be "3.0"
Revisit this please

2017-04-10 08:03 UTC, tochman commented on features/step_definitions/rating_restaurants_steps.rb
> +  within("//form[@class='NisseKebbab']") do
Hardcoded values are not cool 😜 XPATH is not cool 😜

2017-04-10 08:03 UTC, tochman commented on features/step_definitions/rating_restaurants_steps.rb
> +  within("//form[@class='NisseKebbab']") do
```
I select "5" for rating value of "NissesKebbab"
```
```
rest = Restaurant.find_by(....
within(".rest-#{rest.id}") do 
 ....
```

2017-04-11 11:17 UTC, tochman commented
I still think you guys should spend some time on this.

2017-04-12 20:12 UTC, casperjureskog commented on db/migrate/20170406140542_add_ratings_association_to_restaurant.rb
> +    add_reference :ratings, :restaurant, foreign_key: true
yes but i think that it's god to make a separate PR for that and add a user page that list old orders and asks the user to rate used restaurants.

2017-04-12 20:21 UTC, tochman commented on app/controllers/ratings_controller.rb
> +  end
If you duplicate a method like this (you have one in `ShoppingCartsController`) you probably want to raise it a level to the `ApplicationController`

2017-04-12 20:24 UTC, casperjureskog commented on app/controllers/ratings_controller.rb
> +  end
ah yes

2017-04-13 07:21 UTC, tochman commented on app/controllers/ratings_controller.rb
> +  def rate
I would call this method  `create`

2017-04-13 07:30 UTC, casperjureskog commented on app/controllers/ratings_controller.rb
> +  def rate
i think update would be more appropriate in that case because we are not creating a new rating only updating it.

2017-04-14 07:32 UTC, tochman approved these changes

2017-04-14 07:33 UTC, tochman commented
@sigu Can you take a last look at this. @casperjureskog can you please link to the refactoring ticket that came out as a result of this PR in the description?

2017-04-14 07:34 UTC, tochman commented on app/models/rating.rb
> +  end
Please add a ticket to add a spec for this.

2017-04-14 07:54 UTC, casperjureskog commented on app/models/rating.rb
> +  end
Yes, and I added a link to the new PT story in the description.

2017-04-16 09:22 UTC, merged