List restaurants on index page(api)
CraftAcademy/slow_food_online_feb_17 pull request #29
Opened 2017-04-10 15:09 UTC by fottander

PT link: https://www.pivotaltracker.com/story/show/143404131

**Changes proposed in this PR:**
Adds test for listing restaurants on index page
Adds the controller and the route for listing of the restaurant

**What I have learned working on this feature:**
We have learned how to make request specs. 
We have learned how to namespace api routes.

2017-04-10 15:12 UTC, tochman commented
There are no pages in an API. I usually refer to `endpoints`

2017-04-10 17:37 UTC, AmberWilkie commented on app/controllers/api/v1/list_restaurants_controller.rb
> +    render json: {entries: restaurants}
Guys, you can actually view your endpoints by going to the URL (as long as it is a `get` request). See what this gives you. It is likely you want to format this response with `jbuilder`.

2017-04-10 17:37 UTC, AmberWilkie commented on config/routes.rb
> +      resources :list_restaurants, only: [:index], constraints: { format: 'json' }
Nope. This should be `resources :restaurants`

2017-04-10 17:39 UTC, AmberWilkie commented on spec/requests/api/v1/list_restaurants_spec.rb
> +    end
This request spec should have an actual `expected_response` that lists a JSON response from the endpoint with one restaurant. You are deciding how you want to output your response, then making the code do that. How should this data be formatted to make it easy for the client / your front end team to consume it?

2017-04-10 19:42 UTC, tochman commented on app/controllers/api/v1/list_restaurants_controller.rb
> +    render json: {entries: restaurants}
`ListRestaurantsController` sets a narrow scope for this controller. I would suggest `RestaurantsController`

2017-04-10 20:42 UTC, fottander commented on app/controllers/api/v1/list_restaurants_controller.rb
> +    render json: {entries: restaurants}
Alright so it´s ok to have RestaurantsController even if we have another one in the regular controllers?

2017-04-11 10:10 UTC, AmberWilkie commented on app/views/api/v1/restaurants/index.json.jbuilder
> +    json.array! @restaurants.each do |restaurant|
What's with the `!`?

2017-04-11 10:10 UTC, AmberWilkie commented on config/routes.rb
>      end
This `v0` is unnecessary - it was for doing a very simple API endpoint in Cooper.

2017-04-11 10:11 UTC, tochman commented on spec/requests/api/v1/restaurants_spec.rb
> +        }]     }
Please format this part.

2017-04-11 10:12 UTC, tochman commented on spec/requests/api/v1/restaurants_spec.rb
> +      restaurant = create(:restaurant)
This is okay for now but I usually prefer to create my objects using `let` or `let!` 
```
let(:restaurant) { create(:restaurant) }

2017-04-11 10:13 UTC, tochman commented on spec/support/response_json.rb
> +end
👍🏼

2017-04-11 10:13 UTC, tochman requested changes
Small updates needed

2017-04-11 10:38 UTC, fottander commented on config/routes.rb
>      end
Yeah Thomas wanted us to do that before we started on the restaurants. So i guess we can delete those tests now.

2017-04-11 10:57 UTC, fottander commented on app/views/api/v1/restaurants/index.json.jbuilder
> +    json.array! @restaurants.each do |restaurant|
To create the correct endpoint output we needed this here, thomas helped us with this. Probably not an answer but something :)

2017-04-11 11:15 UTC, tochman approved these changes

2017-04-11 11:16 UTC, merged