Index
CraftAcademy/slow_food_online_feb_17 pull request #5
Opened 2017-03-29 09:40 UTC by Scharrre97

Created index page.
* Created list of restaurants

2017-03-29 09:47 UTC, AmberWilkie commented on config/routes.rb
> +  get 'index/index'
Do you need this route / does this do anything? Check `rails routes`

2017-03-29 09:48 UTC, AmberWilkie commented on features/index_page.feature
> +  As soon as I arrive at the index page
User stories should be in this format:
```
Who is affected?
What is the business objective of the action?
What is the action?
```

2017-03-29 09:49 UTC, AmberWilkie commented on features/index_page.feature
> +    And I should see "Indian Restaurant"
I would refactor this to something that you are actually going to display on your index page. Like "Welcome to Slow Food!" or something like that. You are going to replace "list of restaurants" with an actual list of restaurants, so why test for it now?

2017-03-29 09:49 UTC, AmberWilkie commented on npm-debug.log
> +16 verbose exit [ -2, true ]
Put this file in your `.gitignore` and make sure it is removed from the PR.

2017-03-29 09:56 UTC, Scharrre97 commented on features/index_page.feature
> +  As soon as I arrive at the index page
We just want to create an index page to start with.

2017-03-29 09:58 UTC, AmberWilkie commented on features/index_page.feature
> +  As soon as I arrive at the index page
Yes, so you could write something like:
```
As a visitor
in order to access the app
I need to see an index page
```
or `in order to view some food to buy` or some other thing. `As soon as I arrive at the index page` is not a business objective.

2017-03-29 10:05 UTC, tochman commented
There are conflicts and please update the PR description @Scharrre97

2017-03-29 10:06 UTC, tochman commented on features/step_definitions/index_page_steps.rb
> +end
The same step definitions are part of develop already.

2017-03-29 10:07 UTC, tochman commented on config/routes.rb
> +
Please remove empty lines

2017-03-29 11:08 UTC, sigu commented on app/views/index/index.html.haml
> +Thai Restaurant<br>
Can we have this as a list `li` item

2017-03-29 11:08 UTC, sigu commented on features/step_definitions/index_page_steps.rb
> +Given(/^I am on the index page$/) do
To make it less vague we could do `I am on the restaurant index page` ?

2017-03-30 07:00 UTC, Scharrre97 commented on features/step_definitions/index_page_steps.rb
> +Given(/^I am on the index page$/) do
I discuss this with Casper hand he said that we should keep index page because the been working on restaurant page.

2017-03-30 07:29 UTC, tochman requested changes

2017-03-30 07:29 UTC, tochman commented on db/seeds.rb
> +  		name= FFaker::Address.country + " Restaurant",
Mind the code formatting

2017-03-30 07:29 UTC, tochman commented on features/index_page.feature
> +   | Denmark     | Kyra Green  | 0        | Pagacside| Iran, Islamic Republic of |
TBH this does not make sense to me. Not a blocker but the data seems weird

2017-03-30 07:29 UTC, tochman commented on features/index_page.feature
> +   | Denmark     | Kyra Green  | 0        | Pagacside| Iran, Islamic Republic of |
Also, since you are not using most of the attributes for assertions I would allow the factory to set them. Not needed in the table

2017-03-30 07:29 UTC, tochman commented on features/step_definitions/index_page_steps.rb
> +   Restaurant.create!(hash)
Please use factories. 😵

2017-03-30 09:57 UTC, casperjureskog commented on features/step_definitions/index_page_steps.rb
> +  FactoryGirl.create(:restaurant, name: restaurant_name)
add the FactoryGirl matchers and shorten the step def'w by omitting FactoryGirl when you call that in your definitions.

2017-03-30 11:56 UTC, AmberWilkie commented on features/step_definitions/index_page_steps.rb
> +end
There's a new step which was merged from your colleagues. Use that instead (it employs a table) and delete this step.

2017-03-30 12:27 UTC, AmberWilkie approved these changes

2017-03-30 12:35 UTC, tochman approved these changes

2017-03-30 12:35 UTC, merged